-- db/seed.sql
\c job_tracker;

INSERT INTO applications (company, position, date_applied, status, notes)
VALUES
  ('Google', 'Software Engineer', '2023-10-26', 'Applied', 'Submitted application through website.'),
  ('Amazon', 'Frontend Developer', '2023-10-22', 'Interviewing', 'First round interview completed.'),
  ('Microsoft', 'Data Scientist', '2023-10-18', 'Rejected', 'Received rejection email.'),
  ('Facebook', 'Product Manager', '2023-10-15', 'Applied', 'Referred by a friend.'),
  ('Netflix', 'UI/UX Designer', '2023-10-28', 'Applied', 'Portfolio submitted.'),
  ('Tesla', 'Electrical Engineer', '2023-10-25', 'Networking', 'Attended company info session.'),
  ('Spotify', 'Data Analyst', '2023-10-21', 'Applied', 'Completed online assessment.'),
  ('Airbnb', 'Software Engineer Intern', '2023-10-19', 'Offer', 'Accepted internship offer!'),
  ('Uber', 'Product Designer', '2023-10-17', 'Interviewing', 'Second interview scheduled.'),
  ('Pinterest', 'Data Engineer', '2023-10-14', 'Applied', 'Tailored resume and cover letter.'),
  ('Dropbox', 'Backend Developer', '2023-10-12', 'Rejected', 'Not a good fit for the role.'),
  ('LinkedIn', 'Product Marketing Manager', '2023-10-10', 'Applied', 'Networking with employees.'),
  ('Salesforce', 'Sales Development Representative', '2023-10-08', 'Interviewing', 'Preparing for final round interview.'),
  ('Stripe', 'Software Engineer', '2023-10-05', 'Applied', 'Excited about the companys mission.'),
  ('Twitter', 'Data Scientist', '2023-10-03', 'Applied', 'Completed coding challenge.'),
  ('Shopify', 'Frontend Developer', '2023-09-29', 'Interviewing', 'Technical interview scheduled.'),
  ('Square', 'Backend Engineer', '2023-09-27', 'Applied', 'Strong referral from a former colleague.'),
  ('Instacart', 'Product Manager', '2023-09-25', 'Rejected', 'Lack of relevant experience.'),
  ('Lyft', 'Software Engineer Intern', '2023-09-22', 'Applied', 'Hoping to get an interview.'),
  ('Splunk', 'Data Analyst', '2023-09-20', 'Networking', 'Connected with a recruiter on LinkedIn.'),
  ('Adobe', 'UX Researcher', '2023-10-30', 'Applied', 'Submitted portfolio and research samples.'),
  ('Nvidia', 'Machine Learning Engineer', '2023-10-29', 'Interviewing', 'Technical round scheduled next week.'),
  ('IBM', 'Cloud Solutions Architect', '2023-10-27', 'Applied', 'Emphasized cloud certification in application.'),
  ('Zoom', 'DevOps Engineer', '2023-10-24', 'Networking', 'Attended virtual career fair.'),
  ('Slack', 'Product Manager', '2023-10-23', 'Applied', 'Highlighted communication skills in cover letter.'),
  ('Oracle', 'Database Administrator', '2023-10-20', 'Rejected', 'Position filled internally.'),
  ('Twitch', 'Frontend Developer', '2023-10-16', 'Interviewing', 'Completed live coding session.'),
  ('Atlassian', 'Scrum Master', '2023-10-13', 'Applied', 'Emphasized Agile certifications.'),
  ('DocuSign', 'Software Engineer', '2023-10-11', 'Networking', 'Connected with hiring manager on LinkedIn.'),
  ('Palantir', 'Data Engineer', '2023-10-09', 'Applied', 'Submitted through university career portal.'),
  ('Yelp', 'iOS Developer', '2023-10-07', 'Interviewing', 'App demo prepared for next round.'),
  ('VMware', 'Systems Engineer', '2023-10-04', 'Applied', 'Highlighted relevant projects in resume.'),
  ('Snowflake', 'Data Warehouse Specialist', '2023-10-02', 'Networking', 'Attended company webinar.'),
  ('Etsy', 'UX Designer', '2023-09-30', 'Applied', 'Customized portfolio for the role.'),
  ('Twilio', 'Solutions Engineer', '2023-09-28', 'Interviewing', 'Preparing case study presentation.'),
  ('Box', 'Product Marketing Manager', '2023-09-26', 'Applied', 'Emphasized B2B marketing experience.'),
  ('Robinhood', 'Financial Analyst', '2023-09-24', 'Rejected', 'Position requires more years of experience.'),
  ('Unity', 'Game Developer', '2023-09-21', 'Applied', 'Included link to published games.'),
  ('GitLab', 'Technical Writer', '2023-09-19', 'Networking', 'Engaged in company open source projects.'),
  ('Datadog', 'Site Reliability Engineer', '2023-09-17', 'Applied', 'Highlighted monitoring tool experience.'),
  ('Figma', 'Product Designer', '2023-09-15', 'Interviewing', 'Design challenge in progress.'),
  ('Cloudflare', 'Network Engineer', '2023-09-13', 'Applied', 'Emphasized experience with CDNs.'),
  ('Roblox', 'Game Designer', '2023-09-11', 'Networking', 'Attended virtual gaming industry mixer.'),
  ('Asana', 'Technical Program Manager', '2023-09-09', 'Applied', 'Highlighted project management certifications.'),
  ('Coinbase', 'Blockchain Developer', '2023-09-07', 'Interviewing', 'Discussing previous crypto projects.'),
  ('Quora', 'Content Strategist', '2023-09-05', 'Applied', 'Submitted writing samples.'),
  ('Canva', 'Graphic Designer', '2023-09-03', 'Networking', 'Participating in Canva design challenge.'),
  ('Zendesk', 'Customer Success Manager', '2023-09-01', 'Rejected', 'Position filled.'),
  ('Notion', 'Product Manager', '2023-08-30', 'Applied', 'Created Notion page as application.'),
  ('Epic Games', '3D Artist', '2023-08-28', 'Interviewing', 'Portfolio review scheduled.'),
  ('Okta', 'Security Engineer', '2023-08-26', 'Applied', 'Highlighted cybersecurity certifications.'),
  ('Coursera', 'Curriculum Developer', '2023-08-24', 'Networking', 'Connected with course instructors.'),
  ('Hubspot', 'Sales Engineer', '2023-08-22', 'Applied', 'Emphasized CRM experience.'),
  ('MongoDB', 'Database Engineer', '2023-08-20', 'Interviewing', 'Technical assessment completed.'),
  ('Wayfair', 'Supply Chain Analyst', '2023-08-16', 'Rejected', 'Position requires relocation.'),
  ('Duolingo', 'Language Data Scientist', '2023-08-14', 'Applied', 'Mentioned fluency in multiple languages.'),
  ('Squarespace', 'Web Developer', '2023-08-12', 'Networking', 'Attended company tech talk.'),
  ('Zillow', 'Data Analyst', '2023-08-10', 'Interviewing', 'Preparing presentation on housing market trends.'),
  ('Bitly', 'Software Engineer', '2023-08-06', 'Networking', 'Contributed to company''s open-source project.'),
  ('Udacity', 'Course Instructor', '2023-08-04', 'Applied', 'Submitted sample video lecture.'),
  ('Tableau', 'Data Visualization Expert', '2023-07-31', 'Applied', 'Included link to visualization portfolio.'),
  ('Mailchimp', 'Email Marketing Specialist', '2023-07-29', 'Networking', 'Attended digital marketing workshop.'),
  ('Intercom', 'Customer Support Engineer', '2023-07-27', 'Rejected', 'Not enough technical support experience.'),
  ('Unity', 'AR/VR Developer', '2023-07-25', 'Applied', 'Showcased AR app in application.'),
  ('Zapier', 'Integration Specialist', '2023-07-23', 'Interviewing', 'Discussing API integration projects.'),
  ('Airtable', 'Solutions Architect', '2023-07-21', 'Applied', 'Created custom Airtable base as part of application.'),
  ('Miro', 'Product Manager', '2023-07-19', 'Networking', 'Participated in company''s virtual hackathon.'),
  ('Glassdoor', 'Data Analyst', '2023-07-15', 'Interviewing', 'Preparing presentation on job market trends.'),
  ('Upwork', 'Community Manager', '2023-07-13', 'Applied', 'Highlighted freelancing experience.'),
  ('Udemy', 'Content Creator', '2023-07-11', 'Networking', 'Discussing potential course ideas with staff.'),
  ('SurveyMonkey', 'UX Researcher', '2023-07-09', 'Rejected', 'Position put on hold.'),
  ('Grammarly', 'NLP Engineer', '2023-07-07', 'Applied', 'Emphasized language processing projects.'),
  ('Quizlet', 'Educational Content Developer', '2023-07-03', 'Applied', 'Submitted sample study materials.'),
  ('Evernote', 'iOS Developer', '2023-07-01', 'Networking', 'Attended iOS dev meetup hosted by company.'),
  ('Wix', 'Web Designer', '2023-06-29', 'Applied', 'Included portfolio of Wix site designs.'),
  ('Pandora', 'Music Data Analyst', '2023-06-25', 'Applied', 'Highlighted experience with music metadata.'),
  ('Fitbit', 'Firmware Engineer', '2023-06-19', 'Applied', 'Emphasized experience with wearable tech.'),
  ('Patreon', 'Creator Partnerships Manager', '2023-06-17', 'Interviewing', 'Discussing strategies for creator growth.'),
  ('Autodesk', 'CAD Software Engineer', '2023-06-15', 'Applied', 'Included CAD project samples.'),
  ('Plaid', 'Financial Technology Engineer', '2023-06-11', 'Applied', 'Highlighted fintech hackathon wins.'),
  ('Tinder', 'Algorithm Engineer', '2023-06-09', 'Interviewing', 'Discussing matching algorithm improvements.'),
  ('WordPress', 'Theme Developer', '2023-06-07', 'Applied', 'Submitted custom WordPress theme.'),
  ('Fiverr', 'Marketplace Growth Manager', '2023-05-10', 'Applied', 'Highlighted experience in digital marketplaces.'),
  ('Miro', 'UX Researcher', '2023-05-02', 'Applied', 'Included case study on remote collaboration.'),
  ('Figma', 'Design Systems Engineer', '2023-04-22', 'Applied', 'Submitted sample design system documentation.'),
  ('Dropbox', 'Cloud Infrastructure Engineer', '2023-04-20', 'Networking', 'Attended cloud computing conference.'),
  ('Quora', 'Machine Learning Engineer', '2023-04-18', 'Applied', 'Emphasized experience with NLP models.'),
  ('Zendesk', 'Solutions Consultant', '2023-04-16', 'Interviewing', 'Preparing demo of custom Zendesk integration.'),
  ('Trello', 'User Onboarding Specialist', '2023-04-14', 'Applied', 'Included ideas for improving user onboarding flow.')
;